# Generated by Django 6.0.1 on 2026-01-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_fueltype_tbl_adminregistration_tbl_bodytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='image',
            field=models.FileField(upload_to='Assets/image/product'),
        ),
    ]
