# Generated by Django 6.0.1 on 2026-01-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_tbl_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_adminRegistration',
            new_name='tbl_admin',
        ),
    ]
