# Generated by Django 6.0.1 on 2026-01-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_rename_tbl_adminregistration_tbl_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_modelname',
            new_name='tbl_model',
        ),
        migrations.RenameField(
            model_name='tbl_model',
            old_name='modelname',
            new_name='model_name',
        ),
    ]
