# Generated by Django 6.0.1 on 2026-01-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_rename_tbl_modelname_tbl_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueltype',
            old_name='fueltype',
            new_name='fueltype_name',
        ),
        migrations.RenameField(
            model_name='tbl_bodytype',
            old_name='bodytype',
            new_name='bodytype_name',
        ),
        migrations.RenameField(
            model_name='tbl_doorcount',
            old_name='doorcount',
            new_name='doorcount_value',
        ),
        migrations.RenameField(
            model_name='tbl_modelyear',
            old_name='modelyear',
            new_name='modelyear_value',
        ),
        migrations.RenameField(
            model_name='tbl_power',
            old_name='power',
            new_name='power_value',
        ),
        migrations.RenameField(
            model_name='tbl_seatingcapacity',
            old_name='seatingcapacity',
            new_name='seatingcapacity_value',
        ),
        migrations.RenameField(
            model_name='tbl_torque',
            old_name='torque',
            new_name='torque_value',
        ),
        migrations.RenameField(
            model_name='tbl_transmissiontype',
            old_name='transmissiontype',
            new_name='transmissiontype_name',
        ),
    ]
