# Generated by Django 6.0.1 on 2026-01-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_rename_fueltype_fueltype_fueltype_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_drivetrain',
            old_name='drivetrain',
            new_name='drivetrain_type',
        ),
        migrations.RenameField(
            model_name='tbl_mielage',
            old_name='mielage',
            new_name='mielage_value',
        ),
        migrations.RenameField(
            model_name='tbl_odometerreading',
            old_name='odometerreading',
            new_name='odometerreading_value',
        ),
        migrations.RenameField(
            model_name='tbl_ownershipcount',
            old_name='OwnershipCount',
            new_name='OwnershipCount_type',
        ),
        migrations.RenameField(
            model_name='tbl_place',
            old_name='district',
            new_name='district_name',
        ),
        migrations.RenameField(
            model_name='tbl_place',
            old_name='pincode',
            new_name='pincode_value',
        ),
        migrations.RenameField(
            model_name='tbl_place',
            old_name='place',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='tbl_product',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='tbl_product',
            old_name='description',
            new_name='description_text',
        ),
        migrations.RenameField(
            model_name='tbl_product',
            old_name='price',
            new_name='price_value',
        ),
        migrations.RenameField(
            model_name='tbl_product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='tbl_product',
            old_name='subcategory',
            new_name='subcategory_name',
        ),
        migrations.RenameField(
            model_name='tbl_subcategory',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='tbl_subcategory',
            old_name='subcategory',
            new_name='subcategory_name',
        ),
    ]
