# Generated by Django 6.0.1 on 2026-01-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_rename_drivetrain_tbl_drivetrain_drivetrain_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fueltype',
            new_name='tbl_fueltype',
        ),
    ]
