# Generated by Django 6.0.1 on 2026-01-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_enginecapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_engineconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineconfiguration_value', models.CharField(max_length=60)),
            ],
        ),
    ]
