# Generated by Django 6.0.1 on 2026-02-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_engineconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_power',
            name='power_value',
            field=models.CharField(max_length=60),
        ),
    ]
