# Generated by Django 6.0.1 on 2026-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_tbl_power_power_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_mielage',
            name='mielage_value',
        ),
        migrations.RemoveField(
            model_name='tbl_modelyear',
            name='modelyear_value',
        ),
        migrations.RemoveField(
            model_name='tbl_torque',
            name='torque_value',
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_contact',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_odometerreading',
            name='odometerreading_value',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_place',
            name='pincode_value',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='price_value',
            field=models.CharField(max_length=60),
        ),
    ]
