# Generated by Django 6.0.1 on 2026-02-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_remove_tbl_mielage_mielage_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='tbl_mielage',
        ),
        migrations.DeleteModel(
            name='tbl_odometerreading',
        ),
        migrations.DeleteModel(
            name='tbl_power',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='subcategory_name',
        ),
        migrations.DeleteModel(
            name='tbl_torque',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
