# Generated by Django 6.0.1 on 2026-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_tbl_subcategory_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_modelyear',
            name='modelyear_value',
            field=models.IntegerField(null=True),
        ),
    ]
