# Generated by Django 6.0.1 on 2026-02-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_modelyear_modelyear_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_enginecapacity',
        ),
    ]
