# Generated by Django 6.0.1 on 2026-02-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_delete_tbl_enginecapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_model',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_company'),
        ),
    ]
