# Generated by Django 6.0.1 on 2026-01-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.IntegerField(max_length=60)),
                ('RC', models.FileField(upload_to='Assets/image/product')),
            ],
        ),
    ]
