# Generated by Django 6.0.1 on 2026-01-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0010_tbl_engineconfiguration'),
        ('Dealer', '0002_delete_tbl_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.IntegerField(max_length=60)),
                ('vehicle_rc', models.FileField(upload_to='Assets/image/product')),
                ('vehicle_photo', models.FileField(upload_to='Assets/image/product')),
                ('vehicle_power', models.CharField(max_length=60)),
                ('vehicle_torque', models.CharField(max_length=60)),
                ('vehicle_bodytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_bodytype')),
                ('vehicle_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_company')),
                ('vehicle_door_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_doorcount')),
                ('vehicle_drivetrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_drivetrain')),
                ('vehicle_engine_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_enginecapacity')),
                ('vehicle_engine_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_engineconfiguration')),
                ('vehicle_fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_fueltype')),
                ('vehicle_mielage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_mielage')),
                ('vehicle_model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_model')),
                ('vehicle_odometer_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_odometerreading')),
                ('vehicle_ownership_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ownershipcount')),
                ('vehicle_seating_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_seatingcapacity')),
                ('vehicle_transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_transmissiontype')),
            ],
        ),
    ]
