# Generated by Django 6.0.1 on 2026-02-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_tbl_power_power_value'),
        ('Dealer', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_vehicle',
            name='vehicle_model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_modelyear'),
        ),
    ]
