# Generated by Django 6.0.1 on 2026-02-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0004_alter_tbl_vehicle_vehicle_model_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_vehicle',
        ),
    ]
