# Generated by Django 6.0.1 on 2026-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_vehicle',
            name='vehicle_mielage',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_vehicle',
            name='vehicle_odometer_reading',
            field=models.CharField(max_length=60),
        ),
    ]
