# Generated by Django 6.0.1 on 2026-02-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0007_alter_tbl_vehicle_vehicle_mielage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_vehicle',
        ),
    ]
