# Generated by Django 6.0.1 on 2026-02-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='registration_no',
        ),
    ]
