# Generated by Django 6.0.1 on 2026-02-16 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0010_remove_tbl_vehicle_registration_no'),
        ('Guest', '0009_remove_tbl_user_user_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_vehicle',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_dealer'),
        ),
    ]
