# Generated by Django 6.0.1 on 2026-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0011_tbl_vehicle_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_vehicle',
            name='registration_no',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
