# Generated by Django 6.0.1 on 2026-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0012_tbl_vehicle_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_vehicle',
            name='vehicle_engine_capacity',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
