# Generated by Django 6.0.1 on 2026-02-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0013_alter_tbl_vehicle_vehicle_engine_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(upload_to='Assets/image/product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dealer.tbl_vehicle')),
            ],
        ),
    ]
