# Generated by Django 6.0.1 on 2026-02-17 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0014_tbl_gallery'),
        ('Guest', '0009_remove_tbl_user_user_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=60)),
                ('complaint_content', models.CharField(max_length=60)),
                ('complaint_reply', models.CharField(max_length=60)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_date', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=60)),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_amount', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dealer.tbl_vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_datetime', models.CharField(max_length=60)),
                ('rate_value', models.IntegerField(default=0)),
                ('rate_content', models.CharField(max_length=60)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_dealer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
