# Generated by Django 6.0.1 on 2026-02-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0015_tbl_complaint_tbl_booking_tbl_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_booking',
            name='vehicle_id',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.RemoveField(
            model_name='tbl_rating',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='tbl_rating',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
