# Generated by Django 6.0.1 on 2026-02-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0016_remove_tbl_booking_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_vehicle',
            name='vehicle_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
