# Generated by Django 6.0.1 on 2026-02-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0017_tbl_vehicle_vehicle_price'),
        ('User', '0009_delete_tbl_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_bodytype',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_company',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_door_count',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_drivetrain',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_engine_configuration',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_fuel_type',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_model_name',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_model_year',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_ownership_count',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_seating_capacity',
        ),
        migrations.RemoveField(
            model_name='tbl_vehicle',
            name='vehicle_transmission_type',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_vehicle',
        ),
    ]
