# Generated by Django 6.0.1 on 2026-02-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0015_delete_tbl_enginecapacity'),
        ('Dealer', '0018_remove_tbl_vehicle_dealer_and_more'),
        ('Guest', '0009_remove_tbl_user_user_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=60, null=True)),
                ('vehicle_rc', models.FileField(upload_to='Assets/image/product')),
                ('vehicle_photo', models.FileField(upload_to='Assets/image/product')),
                ('vehicle_insurance', models.FileField(upload_to='Assets/image/product')),
                ('vehicle_engine_capacity', models.CharField(max_length=60, null=True)),
                ('vehicle_power', models.CharField(max_length=60)),
                ('vehicle_torque', models.CharField(max_length=60)),
                ('vehicle_mielage', models.CharField(max_length=60)),
                ('vehicle_odometer_reading', models.CharField(max_length=60)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_dealer')),
                ('vehicle_bodytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_bodytype')),
                ('vehicle_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_company')),
                ('vehicle_door_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_doorcount')),
                ('vehicle_drivetrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_drivetrain')),
                ('vehicle_engine_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_engineconfiguration')),
                ('vehicle_fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_fueltype')),
                ('vehicle_model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_model')),
                ('vehicle_model_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_modelyear')),
                ('vehicle_ownership_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ownershipcount')),
                ('vehicle_seating_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_seatingcapacity')),
                ('vehicle_transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_transmissiontype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(upload_to='Assets/image/product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dealer.tbl_vehicle')),
            ],
        ),
    ]
