# Generated by Django 6.0.1 on 2026-01-29 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_rename_tbl_adminregistration_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=60)),
                ('dealer_contact', models.IntegerField(max_length=60)),
                ('dealer_email', models.CharField(max_length=60)),
                ('dealer_password', models.CharField(max_length=60)),
                ('license_no', models.IntegerField(max_length=60)),
                ('establish_date', models.CharField(max_length=60)),
                ('owner_name', models.CharField(max_length=60)),
                ('owner_contact', models.IntegerField(max_length=60)),
                ('owner_aadhar_no', models.IntegerField(max_length=60)),
                ('owner_photo', models.FileField(upload_to='Assets/image/user')),
                ('owner_proof', models.FileField(upload_to='Assets/image/user')),
                ('license_proof', models.FileField(upload_to='Assets/image/user')),
                ('logo', models.FileField(upload_to='Assets/image/user')),
                ('address', models.CharField(max_length=60)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('user_contact', models.IntegerField(max_length=60)),
                ('user_email', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('photo', models.FileField(upload_to='Assets/image/user')),
                ('proof', models.FileField(upload_to='Assets/image/user')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
