# Generated by Django 6.0.1 on 2026-01-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_dealer',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
