# Generated by Django 6.0.1 on 2026-01-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0010_tbl_engineconfiguration'),
        ('Guest', '0002_remove_tbl_user_district_remove_tbl_user_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=60)),
                ('dealer_contact', models.IntegerField(max_length=60)),
                ('dealer_email', models.CharField(max_length=60)),
                ('dealer_password', models.CharField(max_length=60)),
                ('license_no', models.IntegerField(max_length=60)),
                ('establish_date', models.CharField(max_length=60)),
                ('owner_name', models.CharField(max_length=60)),
                ('owner_contact', models.IntegerField(max_length=60)),
                ('owner_aadhar_no', models.IntegerField(max_length=60)),
                ('owner_photo', models.FileField(upload_to='Assets/image/user')),
                ('owner_proof', models.FileField(upload_to='Assets/image/user')),
                ('license_proof', models.FileField(upload_to='Assets/image/user')),
                ('dealer_logo', models.FileField(upload_to='Assets/image/user')),
                ('dealer_address', models.CharField(max_length=60)),
                ('dealer_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
                ('dealer_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('user_contact', models.IntegerField(max_length=60)),
                ('user_email', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=60)),
                ('user_confirmpassword', models.CharField(max_length=60)),
                ('user_address', models.CharField(max_length=60)),
                ('user_photo', models.FileField(upload_to='Assets/image/user')),
                ('user_proof', models.FileField(upload_to='Assets/image/user')),
                ('user_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
                ('user_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
