# Generated by Django 6.0.1 on 2026-02-10 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_dealer',
            name='dealer_confirmpassword',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
