# Generated by Django 6.0.1 on 2026-02-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_dealer_dealer_confirmpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_dealer',
            name='dealer_district',
        ),
    ]
