# Generated by Django 6.0.1 on 2026-02-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_remove_tbl_dealer_dealer_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_dealer',
            name='dealer_confirmpassword',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_confirmpassword',
        ),
    ]
