# Generated by Django 6.0.1 on 2026-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_remove_tbl_dealer_dealer_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_dealer',
            name='dealer_logo',
            field=models.FileField(upload_to='Assets/image/dealer'),
        ),
        migrations.AlterField(
            model_name='tbl_dealer',
            name='license_proof',
            field=models.FileField(upload_to='Assets/image/dealer'),
        ),
        migrations.AlterField(
            model_name='tbl_dealer',
            name='owner_photo',
            field=models.FileField(upload_to='Assets/image/dealer'),
        ),
        migrations.AlterField(
            model_name='tbl_dealer',
            name='owner_proof',
            field=models.FileField(upload_to='Assets/image/dealer'),
        ),
    ]
