# Generated by Django 6.0.1 on 2026-02-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_alter_tbl_dealer_dealer_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_dealer',
            name='dealer_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_dealer',
            name='dealer_contact',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_dealer',
            name='license_no',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_dealer',
            name='owner_aadhar_no',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tbl_dealer',
            name='owner_contact',
            field=models.CharField(max_length=60),
        ),
    ]
