# Generated by Django 6.0.1 on 2026-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_dealer_dealer_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_district',
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_contact',
            field=models.CharField(max_length=60),
        ),
    ]
