# Generated by Django 6.0.1 on 2026-02-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
