# Generated by Django 6.0.1 on 2026-02-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_tbl_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rating',
            name='rate_datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
