# Generated by Django 6.0.1 on 2026-02-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_tbl_rating_rate_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
