# Generated by Django 6.0.1 on 2026-02-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_tbl_complaint_complaint_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
