# Generated by Django 6.0.1 on 2026-03-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_message',
        ),
    ]
