# Generated by Django 6.0.1 on 2026-03-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0019_initial'),
        ('Guest', '0009_remove_tbl_user_user_district_and_more'),
        ('User', '0017_delete_tbl_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=60)),
                ('message_content', models.CharField(max_length=60)),
                ('message_reply', models.CharField(max_length=60)),
                ('message_status', models.IntegerField(default=0)),
                ('message_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dealer.tbl_vehicle')),
            ],
        ),
    ]
